[book]
authors = ["yxj"]
language = "en"
multilingual = false
src = "src"
title = "MusicTraining Docs Try"

[output.html]
git-repository-url = "https://yang-xijie.github.io/MusicHelper/"
git-repository-icon = "fa-github"
